#!/bin/bash
# Resolve all frontend dependencies that the application requires to develop.

# Stop on errors
set -e

cd "$(dirname "$0")/.."

node ./script/merge_requirements.js
node ./script/inject_translations.js
yarn install
