#!/bin/bash
# Run the frontend development server

# Stop on errors
set -e

cd "$(dirname "$0")/.."

if [ ! -d "./node_modules" ]; then
    echo "Directory /node_modules DOES NOT exists."
    echo "Running yarn install"
    yarn install
fi

NODE_OPTIONS=--max_old_space_size=6144 ./node_modules/.bin/gulp build-hacs